# permissions for end users to edit backupstoragelocations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backupstoragelocation-editor-role
rules:
- apiGroups:
  - velero.io.my.domain
  resources:
  - backupstoragelocations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - velero.io.my.domain
  resources:
  - backupstoragelocations/status
  verbs:
  - get
