# permissions for end users to view backupstoragelocations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backupstoragelocation-viewer-role
rules:
- apiGroups:
  - velero.io.my.domain
  resources:
  - backupstoragelocations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - velero.io.my.domain
  resources:
  - backupstoragelocations/status
  verbs:
  - get
