apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: prototype-non-admin.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: testing
  displayName: testing
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - testing
  links:
  - name: Prototype Non Admin
    url: https://prototype-non-admin.domain
  maintainers:
  - email: shurley@redhat.com
    name: shawn
  maturity: alpha
  provider:
    name: redhat
  version: 0.0.0
